global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Maui.Core;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Pizza.Maui.Pages;
global using Pizza.Maui.Services;
global using Pizza.Maui.ViewModels;
global using System.Collections.ObjectModel;
